-- changeset init-tasks-:002

CREATE TABLE IF NOT EXISTS tasks
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id        UUID,
    task_status     SMALLINT                                NOT NULL,
    process_step    SMALLINT                                NOT NULL,
    attempts        INTEGER,
    next_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);